apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.acme.corp
spec:
  group: acme.corp
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  databaseName:
                    type: string
                    minLength: 3
                  databaseEngine:
                    type: string
                    enum: ["postgresql", "mysql"]
                    default: "postgresql"
                  size:
                    type: string
                    enum: ["small", "medium", "large"]
                    default: "small"
                  team:
                    type: string
                required:
                - databaseName
                - team
            required:
            - parameters